# Generated by Django 3.1 on 2020-08-10 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=100, verbose_name='Вопрос')),
                ('answer', models.CharField(max_length=300, verbose_name='Ответ')),
                ('add_date', models.DateField(auto_now_add=True, verbose_name='Дата Добавления')),
                ('repeat_date', models.DateField(verbose_name='Дата Повторения')),
            ],
            options={
                'verbose_name': 'Карточка',
                'verbose_name_plural': 'Карточки',
            },
        ),
    ]
