# Generated by Django 3.1 on 2020-08-11 11:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('study_helper_app', '0002_auto_20200810_1308'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='study_helper_app.category', verbose_name='Категория'),
        ),
    ]
