# Generated by Django 3.1 on 2020-08-12 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('study_helper_app', '0003_auto_20200811_1123'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='repeat_date',
            field=models.DateField(auto_now_add=True, verbose_name='Дата Повторения'),
        ),
    ]
