# Generated by Django 3.1 on 2020-08-13 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('study_helper_app', '0004_auto_20200812_0739'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='repeat_date',
            field=models.DateField(auto_now_add=True, null=True, verbose_name='Дата Повторения'),
        ),
    ]
