# Generated by Django 3.1 on 2020-08-13 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('study_helper_app', '0005_auto_20200813_1147'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='repeat_date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата Повторения'),
        ),
    ]
