# Generated by Django 3.1 on 2020-08-13 12:35

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('study_helper_app', '0006_auto_20200813_1151'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='repeat_date',
            field=models.DateField(default=datetime.datetime(2020, 8, 13, 12, 35, 39, 952806, tzinfo=utc), verbose_name='Дата Повторения'),
        ),
    ]
