# Generated by Django 3.1 on 2020-08-14 12:18

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('study_helper_app', '0007_auto_20200813_1235'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='answer',
            field=models.CharField(max_length=500, verbose_name='Ответ'),
        ),
        migrations.AlterField(
            model_name='cart',
            name='repeat_date',
            field=models.DateField(default=datetime.datetime(2020, 8, 14, 12, 18, 50, 759229, tzinfo=utc), verbose_name='Дата Повторения'),
        ),
    ]
