# Generated by Django 3.1 on 2020-08-15 10:27

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('study_helper_app', '0008_auto_20200814_1218'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='question',
            field=models.CharField(max_length=200, verbose_name='Вопрос'),
        ),
        migrations.AlterField(
            model_name='cart',
            name='repeat_date',
            field=models.DateField(default=datetime.datetime(2020, 8, 15, 10, 27, 34, 917916, tzinfo=utc), verbose_name='Дата Повторения'),
        ),
    ]
