# Generated by Django 3.1 on 2020-08-15 10:27

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('study_helper_app', '0009_auto_20200815_1027'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='repeat_date',
            field=models.DateField(default=datetime.datetime(2020, 8, 15, 10, 27, 52, 159381, tzinfo=utc), verbose_name='Дата Повторения'),
        ),
    ]
