# Generated by Django 3.1 on 2020-08-16 07:31

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('study_helper_app', '0010_auto_20200815_1027'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Режим',
                'verbose_name_plural': 'Все Режимы',
            },
        ),
        migrations.AlterField(
            model_name='cart',
            name='repeat_date',
            field=models.DateField(default=datetime.datetime(2020, 8, 16, 7, 31, 50, 785095, tzinfo=utc), verbose_name='Дата Повторения'),
        ),
        migrations.CreateModel(
            name='Stage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='Название')),
                ('interval', models.DecimalField(decimal_places=1, max_digits=5, verbose_name='Интервал (в часах)')),
                ('sequence', models.IntegerField(unique=True, verbose_name='Последовательность')),
                ('mode', models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='study_helper_app.mode', verbose_name='Режим')),
            ],
            options={
                'verbose_name': 'Стадия',
                'verbose_name_plural': 'Стадии',
            },
        ),
        migrations.AddField(
            model_name='category',
            name='mode',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='study_helper_app.mode', verbose_name='Режим'),
        ),
    ]
