# Generated by Django 3.1 on 2020-08-16 08:02

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('study_helper_app', '0011_auto_20200816_0731'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='stage',
            field=models.IntegerField(default=0, verbose_name='Стадия'),
        ),
        migrations.AlterField(
            model_name='cart',
            name='repeat_date',
            field=models.DateField(default=datetime.datetime(2020, 8, 16, 8, 2, 54, 869564, tzinfo=utc), verbose_name='Дата Повторения'),
        ),
    ]
