# Generated by Django 3.1 on 2020-08-18 08:23

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('study_helper_app', '0013_auto_20200816_1209'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stage',
            name='interval',
        ),
        migrations.AddField(
            model_name='stage',
            name='interval_day',
            field=models.IntegerField(default=0, verbose_name='Интервал (в днях)'),
        ),
        migrations.AddField(
            model_name='stage',
            name='interval_hour',
            field=models.IntegerField(default=0, verbose_name='Интервал (в часах)'),
        ),
        migrations.AddField(
            model_name='stage',
            name='interval_minute',
            field=models.IntegerField(default=0, verbose_name='Интервал (в минутах)'),
        ),
        migrations.AddField(
            model_name='stage',
            name='interval_month',
            field=models.IntegerField(default=0, verbose_name='Интервал (в месяцах)'),
        ),
        migrations.AlterField(
            model_name='cart',
            name='repeat_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 8, 18, 8, 23, 5, 702891, tzinfo=utc), verbose_name='Дата Повторения'),
        ),
    ]
