# Generated by Django 3.1 on 2020-08-20 06:31

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('study_helper_app', '0016_auto_20200819_0833'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='cart',
            name='repeat_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 8, 20, 6, 31, 56, 912190, tzinfo=utc), verbose_name='Дата Повторения'),
        ),
    ]
