# Generated by Django 3.1 on 2020-08-22 08:12

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('study_helper_app', '0017_auto_20200820_0631'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='session_id',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='cart',
            name='repeat_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 8, 22, 8, 12, 34, 301081, tzinfo=utc), verbose_name='Дата Повторения'),
        ),
    ]
