# Generated by Django 3.1 on 2020-08-22 08:15

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('study_helper_app', '0018_auto_20200822_0812'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='session_id',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='cart',
            name='repeat_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата Повторения'),
        ),
    ]
